stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "mkt-be-image:v1.0"
  CONTAINER_NAME: "mkt-be-container"

build_dev:
  stage: build
  tags:
    - cleverjob-runner-dev
  allow_failure: false
  script:
    - echo 'Start build'
    - cp $APPLICATION_DEV $CI_PROJECT_DIR/src/main/resources/application.properties
    - git log --oneline -10
    - docker build -t $IMAGE_NAME .
  only:
    - /^dev-.*$/

deploy_dev:
  stage: deploy
  tags:
    - cleverjob-runner-dev
  environment:
    name: development
  script:
    - echo 'stop container...'
    - docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
    - git log --oneline -10
    - echo 'start deploying...'
    - docker run --log-driver=syslog --log-opt syslog-address=tcp://:5000 --log-opt syslog-facility=daemon --network="host" -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME
    - echo 'build done'
    - echo 'script for deploying on DEV branch'
    - echo 'DEPLOYED SUCCESSFULLY'
    - exit
  only:
    - /^dev-.*$/